### PR TITLE
CAD Design used 

### LINKED ISSUE #4: Add CAD_Design folder
- Add the mechanical cad model of the robot
- should include stl as well as solidworks file.

### PR DESCRIPTION
**Pull request by VaradNaik921**
CAD Designs of Rigid Bot and Molds used for Fabrication of the Robot

### CODE REVIEW

**Comment by ChinmayMundane** [comment]
comment which issue it solves

**Comment by VaradNaik921** [comment]
Add CAD_Design Folder issue solved

**Comment by ChinmayMundane** [comment]
include both prototypes, right now i only see one

**Comment by ChinmayMundane** [comment]
update your branch with respect to main otherwise it can't be merged

**Comment by VaradNaik921** [comment]
This Solves #7
Includes:
 - Assembly
 - Components
 - Rigid_Bot_Design
 - STL_Files
 - Soft_Quad_Molds
 - assets
 - README.md

**Pull request merged**
